### ISSUE TITLE
rSOILWAT2 reads/writes carbon data

### ISSUE THREAD

**Issue by dschlaep** [Burke-Lauenroth-Lab/rSOILWAT2#57]
rSOILWAT2 must be able to receive/read carbon data instead of relying on SOILWAT2 to read it from carbon.in.

The current setup with passing an explicit dir argument to sw_exec is hiding a logical error:
- e.g., https://github.com/Burke-Lauenroth-Lab/rSFSW2/pull/115/commits/ef18f0ee5e2e859cfe0c0f551672aca372433e26) is incorrect because `project_paths[["dir_in_sw"]]` only holds the default values and not the run-specific values.
- rSOILWAT2 unit tests `test_exec_and_aggregate.R` fail because all values should be passable as arguments and not read after the fact from file

**Comment by Zachary-Kramer** [comment]
I don't fully understand the meaning of "rSOILWAT2 must be able to read carbon data", as I thought it just used SOILWAT2 to do that. Does this mean swCarbon needs a swReadLines method?

**Comment by dschlaep** [comment]
While `SOILWAT2` stand-alone runs with inputs derived from files on disk, `rSOILWAT2` (and its use by `rSFSW2`) remove the (file-system and time) bottleneck of reading (and writing) files from/to disk by passing all inputs to `SOILWAT2` as objects in memory. This abstraction requires that `rSOILWAT2` (and `rSFSW2`) acquire all inputs independently from the `SOILWAT2` input mechanism.

During runs of `rSFSW2` and possibly simulations with `rSOILWAT2`, the set of input files required by any `SOILWAT2` run, does never exist at all -- thus, the mechanism of `SOILWAT2` to read input files cannot be used to input data.

**Comment by Zachary-Kramer** [comment]
Ok. There are three S4 classes that need to modified, then. This will be a little time consuming, because currently SOILWAT2 calculates the multipliers per line of the .in file, and it will have to have an alternate function called by rSOILWAT2 that calculates them based off of passed in input data, or just have the function be completely modified to work with either option. 

I've already started dealing with the CO2Coefficients in prod.in, and, seeing how tedious it is, I'm expecting the three classes to take up all of my time this week.
