### ISSUE TITLE
Enhance slot `CO2ppm` of class `swCarbon` to 2-column matrix

### ISSUE THREAD

**Issue by dschlaep** [Burke-Lauenroth-Lab/rSOILWAT2#75]
The slot CO2ppm of class swCarbon is currently a vector. I believe that this should be a matrix with two columns: `Year` and the value. Otherwise, it is not as obvious what the code does and what any value means -- difficult to maintain.

Also this class should gain a validity method that performs the checks which are currently in `rSFSW2`, i.e., that all CO2 concentration values are not NA and that they are positive.

**Comment by Zachary-Kramer** [comment]
Keep in mind that SOILWAT2 still expects a vector:
```
  TimeInt year;
  for (year = SW_Model.startyr + c->addtl_yr; year <= SW_Model.endyr + c->addtl_yr; year++)
  {
    c->ppm[year] = REAL(GET_SLOT(object, install("CO2ppm")))[year - 1];  // R's index is 1-based
  }
```

This will need to be updated, too

**Comment by dschlaep** [comment]
done

**Comment by Zachary-Kramer** [comment]
The code added is not functional. There is a compilation issue, but I will push the simple fix. The main issue is that there are no slots in CO2ppm (see runDataSC of any CO2 run with this code, it will show that the slot "Year" could not be accessed). I believe this is because data frames are not S4 classes, so you cannot use the GET_SLOT function on the SEXP object? I could be wrong, but I can't find any documentation online supporting the idea of passing a data.frame and accessing it with GET_SLOT.

Doesn't swWeather's approach seem correct? It uses a matrix. If swCarbon used the same approach then it could likely access the data like this: `if (year == *INTEGER(GET_SLOT(VECTOR_ELT(CO2ppm, i - 1), install("Year"))))`

I've tested this out a bit. Do you want to fix this or do you want me to continue looking into it?

**Comment by dschlaep** [comment]
Yep, thanks! I working on this.
