### ISSUE TITLE
onSet_swCarbon: Figure out why i is over 180,000

### ISSUE THREAD

**Issue by dschlaep** [Burke-Lauenroth-Lab/rSOILWAT2#80]
@Zachary-Kramer commented in commit https://github.com/Burke-Lauenroth-Lab/SOILWAT2/commit/b6c326310503d9686074f665c19dd96e82e6b678 inside function `onSet_swCarbon`:
```
// TODO: Figure out why i is over 180,000
  if (i - 1 + n_sim > n_input)
  {
    LogError(logfp, LOGFATAL, "%s : CO2ppm object does not contain data for every year");
  }
```

**Comment by dschlaep** [comment]
I cannot reproduce this (with commit https://github.com/Burke-Lauenroth-Lab/SOILWAT2/commit/179f83b0f23d3a60904ef8f6c9e0f0ac35fc175a that added a `debug` print statements to the function `onSet_swCarbon`

```
path_demo3 <- system.file("extdata", "example3", package = "rSOILWAT2")
sw_in6 <- sw_inputDataFromFiles(dir = path_demo3, files.in = "files_v31.in")
sw_out6 <- sw_exec(inputData = sw_in6)

'onSet_swCarbon': year = 1979, n_sim = 32, n_input = 32, i = 1
ppm[year = 1979] = 336.52 <-> S4[i = 1] = 336.52
ppm[year = 1980] = 338.36 <-> S4[i = 2] = 338.36
ppm[year = 1981] = 339.73 <-> S4[i = 3] = 339.73
ppm[year = 1982] = 340.79 <-> S4[i = 4] = 340.79
ppm[year = 1983] = 342.20 <-> S4[i = 5] = 342.20
ppm[year = 1984] = 343.78 <-> S4[i = 6] = 343.78
ppm[year = 1985] = 345.28 <-> S4[i = 7] = 345.28
ppm[year = 1986] = 346.80 <-> S4[i = 8] = 346.80
ppm[year = 1987] = 348.64 <-> S4[i = 9] = 348.64
ppm[year = 1988] = 350.74 <-> S4[i = 10] = 350.74
ppm[year = 1989] = 352.49 <-> S4[i = 11] = 352.49
ppm[year = 1990] = 353.86 <-> S4[i = 12] = 353.86
ppm[year = 1991] = 355.02 <-> S4[i = 13] = 355.02
ppm[year = 1992] = 355.88 <-> S4[i = 14] = 355.88
ppm[year = 1993] = 356.78 <-> S4[i = 15] = 356.78
ppm[year = 1994] = 358.13 <-> S4[i = 16] = 358.13
ppm[year = 1995] = 359.84 <-> S4[i = 17] = 359.84
ppm[year = 1996] = 361.46 <-> S4[i = 18] = 361.46
ppm[year = 1997] = 363.15 <-> S4[i = 19] = 363.15
ppm[year = 1998] = 365.32 <-> S4[i = 20] = 365.32
ppm[year = 1999] = 367.35 <-> S4[i = 21] = 367.35
ppm[year = 2000] = 368.87 <-> S4[i = 22] = 368.87
ppm[year = 2001] = 370.47 <-> S4[i = 23] = 370.47
ppm[year = 2002] = 372.52 <-> S4[i = 24] = 372.52
ppm[year = 2003] = 374.76 <-> S4[i = 25] = 374.76
ppm[year = 2004] = 376.81 <-> S4[i = 26] = 376.81
ppm[year = 2005] = 378.81 <-> S4[i = 27] = 378.81
ppm[year = 2006] = 380.83 <-> S4[i = 28] = 380.83
ppm[year = 2007] = 382.78 <-> S4[i = 29] = 382.78
ppm[year = 2008] = 384.80 <-> S4[i = 30] = 384.80
ppm[year = 2009] = 387.01 <-> S4[i = 31] = 387.01
ppm[year = 2010] = 389.32 <-> S4[i = 32] = 389.32
```

**Comment by dschlaep** [comment]
@Zachary-Kramer Could you please provide a reproducible example?

**Comment by Zachary-Kramer** [comment]
Have you done a full run in rSFSW2 without it crashing? The issue is that my rSFSW2 project is providing data from 1980-2010, which causes `i` to become a massive number due to never matching `SW_Model.startyr` (1979). The example you gave is using SOILWAT2 inputs, which is not my issue (this is strictly a rSFSW2 data gathering issue).

When I look at `isim_time$useyrs`, which determines which years are being grabbed from LookupCarbonScenario, it is a sequence from 1980-2010. I tried to understand why it is like this by looking at the `sim_time$` variables:

`useyrs` (sequence from 1980 to 2010) is determined by `startyr:endyr` (1980:2010). `startyr` is 1980 as defined in the description file. The only way for `startyr` to be something different is when `spinup_N` is not null, which means it is predefined in the description file. When it is defined, `startyr` is equal to `simstartyr + spinup_N`. So, the only possible way I see this working with `useyrs` is to have `spinup_N` defined as 0, or both the `simstartyr` and `startyr` as equal. From my searches, it appears that almost every other part of the code uses `simstartyr:endyr`, not `startyr:endyr`. What aspect of `useyrs` am I not understanding? Why did you opt to use it instead of the `simstartyr:endyr`?

When I use `simstartyr:endyr`, there are no issues.

**Comment by dschlaep** [comment]
It is correct behavior that the code fails if data are provided for 1980:2010 but data are required for 1979:2010.

It seems that the code in rSFSW2 should extract CO2-concentration data for `simstartyr:endyr` as you conclude.

**Comment by Zachary-Kramer** [comment]
Yes, it is correct behavior. I believe I was just confused because the error message caused a fatal crash (recently fixed), which made it seem like the comparison with `i` was not behaving as intended.

I will update the extraction in rSFSW2. Regardless, I believe this issue can be closed now.

Thanks
